background_opacity 0.8
background_blur 20

hide_window_decorations titlebar-only

window_padding_width 20

confirm_os_window_close 0

tab_bar_style powerline
tab_powerline_style round
tab_bar_align center
tab_bar_background none
tab_bar_margin_width 6
tab_bar_margin_height 6 2
tab_title_template " {'АБВГДЂЕЖЗИЈКЛЉМНЊОПРСТЋУФХЦЧЏШ'[(index - 1) % 30]} "
active_tab_font_style bold
inactive_tab_font_style normal
active_tab_foreground #ffffff
active_tab_background #45475a
inactive_tab_foreground #9399b2
inactive_tab_background #24252e

map cmd+t new_tab_with_cwd

map cmd+h previous_tab
map cmd+l next_tab
